package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// BuildSSHArgs constructs the argument slice for the ssh command.
// If portable is true, identities under $HOME are displayed as ~/.ssh/...
func BuildSSHArgs(e Entry, keysDir string, portable bool) []string {
	var args []string

	if e.Port > 0 && e.Port != 22 {
		args = append(args, "-p", strconv.Itoa(e.Port))
	}

	identity := e.ResolvedIdentity(keysDir)
	if identity != "" {
		idPath := identity
		if portable {
			idPath = DisplayPath(identity)
		}
		args = append(args, "-i", idPath)
	}

	if e.ProxyJump != "" {
		args = append(args, "-J", e.ProxyJump)
	}

	// Filter out -i <val> from ExtraArgs if already handled
	for i := 0; i < len(e.ExtraArgs); i++ {
		arg := e.ExtraArgs[i]
		if (arg == "-i" || arg == "--identity-file") && i+1 < len(e.ExtraArgs) {
			i++
			continue
		}
		args = append(args, arg)
	}

	target := e.Host
	if e.User != "" {
		target = e.User + "@" + e.Host
	}
	args = append(args, target)

	return args
}

// BuildSSHCommandString constructs the complete runnable command line.
func BuildSSHCommandString(name string, e Entry, keysDir string) string {
	args := BuildSSHArgs(e, keysDir, true)
	var parts []string
	parts = append(parts, "ssh")
	for _, a := range args {
		if strings.ContainsAny(a, " \t\n\"'$") {
			parts = append(parts, fmt.Sprintf("%q", a))
		} else {
			parts = append(parts, a)
		}
	}
	return strings.Join(parts, " ")
}

// GenerateShellDefinition generates a shell function or alias for a given entry.
func GenerateShellDefinition(name string, e Entry, keysDir string, format, shellType string) string {
	cmdStr := BuildSSHCommandString(name, e, keysDir)
	var sb strings.Builder

	if e.Description != "" {
		sb.WriteString(fmt.Sprintf("# %s: %s\n", name, e.Description))
	}

	switch shellType {
	case "fish":
		if format == "alias" {
			sb.WriteString(fmt.Sprintf("alias %s %q\n", name, cmdStr))
		} else {
			sb.WriteString(fmt.Sprintf("function %s\n    %s $argv\nend\n", name, cmdStr))
		}
	default: // zsh, bash, sh
		if format == "alias" {
			sb.WriteString(fmt.Sprintf("alias %s=%q\n", name, cmdStr))
		} else {
			// Functions allow passing arguments like `prod1 ls -la` or `prod1 -L 8080:localhost:8080`
			sb.WriteString(fmt.Sprintf("%s() {\n    %s \"$@\"\n}\n", name, cmdStr))
		}
	}

	return sb.String()
}

// GenerateAll generates all shell definitions for all entries in Config.
func GenerateAll(cfg Config, format, shellType string) string {
	var sb strings.Builder
	sb.WriteString("# --------------------------------------------------------\n")
	sb.WriteString("# Generated by kgssh (SSH Alias Manager)\n")
	sb.WriteString("# Automatically updated by 'kgssh sync', 'kgssh add', and 'kgssh remove'\n")
	sb.WriteString("# Source this file in your ~/.zshrc or ~/.bashrc:\n")
	sb.WriteString("#   [ -f ~/.kgssh/aliases.sh ] && source ~/.kgssh/aliases.sh\n")
	sb.WriteString("# --------------------------------------------------------\n\n")

	names := make([]string, 0, len(cfg.Entries))
	for name := range cfg.Entries {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		sb.WriteString(GenerateShellDefinition(name, cfg.Entries[name], cfg.KeysDir, format, shellType))
		sb.WriteString("\n")
	}

	return sb.String()
}

// ResolveAliasesFilePath returns the path to ~/.kgssh/aliases.sh.
func ResolveAliasesFilePath() string {
	home := userHomeDir()
	return filepath.Join(home, ".kgssh", "aliases.sh")
}

// SyncAliasesFile writes the generated aliases to the target file.
func SyncAliasesFile(cfg Config, filePath, format, shellType string) error {
	if filePath == "" {
		filePath = ResolveAliasesFilePath()
	}
	if err := os.MkdirAll(filepath.Dir(filePath), 0o755); err != nil {
		return fmt.Errorf("create dir for aliases: %w", err)
	}
	content := GenerateAll(cfg, format, shellType)
	return os.WriteFile(filePath, []byte(content), 0o644)
}

// InstallShellHook checks ~/.zshrc or ~/.bashrc and adds source line if not already present.
func InstallShellHook(rcPath, aliasFilePath string) (bool, error) {
	if rcPath == "" {
		home := userHomeDir()
		zshrc := filepath.Join(home, ".zshrc")
		bashrc := filepath.Join(home, ".bashrc")
		if _, err := os.Stat(zshrc); err == nil {
			rcPath = zshrc
		} else if _, err := os.Stat(bashrc); err == nil {
			rcPath = bashrc
		} else {
			rcPath = zshrc
		}
	}

	if aliasFilePath == "" {
		aliasFilePath = ResolveAliasesFilePath()
	}

	// Portable display path for shell rc
	portablePath := DisplayPath(aliasFilePath)
	hookLine := fmt.Sprintf(`[ -f %s ] && source %s`, portablePath, portablePath)

	// Check if already in rc file
	data, err := os.ReadFile(rcPath)
	if err == nil {
		scanner := bufio.NewScanner(strings.NewReader(string(data)))
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if strings.Contains(line, "aliases.sh") || strings.Contains(line, aliasFilePath) {
				return false, nil // already installed
			}
		}
	}

	// Append hook
	f, err := os.OpenFile(rcPath, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return false, fmt.Errorf("open %s: %w", rcPath, err)
	}
	defer f.Close()

	snippet := fmt.Sprintf("\n# kgssh SSH Alias Manager\n%s\n", hookLine)
	if _, err := f.WriteString(snippet); err != nil {
		return false, fmt.Errorf("write to %s: %w", rcPath, err)
	}

	return true, nil
}
